export const FILE_CONSTANTS = {
  BINARY_DETECTION_BUFFER_SIZE: 8192,

  MAX_IN_MEMORY_FILE_SIZE: 1024 * 1024,

  STREAM_THRESHOLD: 10 * 1024 * 1024,

  MAX_MEMORY_FILES: 1000,

  MAX_SAFE_FILE_SIZE: 100 * 1024 * 1024,
} as const;

export const PERFORMANCE_CONSTANTS = {
  MAX_CONCURRENT_FILE_OPERATIONS: 8,

  PROGRESS_UPDATE_INTERVAL: 100,
} as const;

export const WATCH_CONSTANTS = {
  DEFAULT_DEBOUNCE_MS: 500,

  MIN_DEBOUNCE_MS: 100,

  MAX_DEBOUNCE_MS: 5000,
} as const;

export const GLOB_CONSTANTS = {
  DEFAULT_PATTERN: "**/*",
} as const;
